version: '3.1'

services:
  database:
    mem_limit: 2048m
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network

  #Decomment this sectiom if you need phpmyadmin
  #phpmyadmin:
  #  depends_on:
  #    - database
  #  image: phpmyadmin:5.2.1-apache
  #  restart: unless-stopped
  #  ports:
  #    - 8081:80
  #  env_file: .env
  #  environment:
  #    PMA_HOST: database
  #    MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  #  networks:
  #    - wordpress-network

  wordpress:
    depends_on:
      - database
    image: wordpress:5.4.0-apache
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wordpress-plugin/onelogin-saml-sso/:/var/www/html/wp-content/plugins/onelogin-saml-sso/
      - ./wordpress-theme/italiawp2/:/var/www/html/wp-content/themes/italiawp2/
      - ./onelogin_custom_settings/functions.php:/var/www/html/wp-content/plugins/onelogin-saml-sso/php/functions.php
      - ./onelogin_custom_settings/configuration.php:/var/www/html/wp-content/plugins/onelogin-saml-sso/php/configuration.php
      - ./onelogin_custom_settings/settings.php:/var/www/html/wp-content/plugins/onelogin-saml-sso/php/settings.php
      - ./italiaWP2_custom_settings/header.php:/var/www/html/wp-content/themes/italiawp2/header.php
    networks:
      - wordpress-network

volumes:
  db-data:

networks:
  wordpress-network:
    driver: bridge